name: suggester
description: Autocompletion engine with highly configurable partial matching. Suitable for web or mobile.
version: 0.9.7
homepage: https://github.com/derbec/suggester

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  meta: ^1.3.0
  collection: ^1.15.0
  ternarytreap: ^2.0.5

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.8
